sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/CollectiveDecentralizedJudgements.tex
- bibtex _build/CollectiveDecentralizedJudgements
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/CollectiveDecentralizedJudgements.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/CollectiveDecentralizedJudgements.tex
deploy:
  provider: releases
  api_key:
    secure: aDDrOSFciYws1DVE7ZvjmvHnk477z+IFxJZZ/Uo1FwRcx09o3oTfmVdZWbFofvPLsd652y7yaw+uVPAeyL85D6+ZJ32IB6ai51RwdV2qHUtsao/jMLK5MdYxmfU4zpt7wvf3aOcSHy5yPOxJzjijl1LOavBOwMu+KpR7kjHuAWy/ptmR+68Nk3g+IknSKHFDlMyLUO04WPX4ilzhBjCYG+CSZBUJmVQrsihnErj6cq4d2rVsmUrX1ukma5rrjK9TX98locZ36QD4s88ZT7djDwG2n2wl3I4QFe8zrINvvDG4cVN8dvV3vplvGfNbPuFhplgmvv9Q54O5Q0WkooUSVkWdfyfIC8QdNQldcVROffF2BV0X+RFvS+CG79ejszSiFn60TPO63AhER9QPa1g/2k0Lrjk8ylhjABdjxaAy7vGoi7gtE5hslYVTAFpnbJzEXd23fgj7xAMfRF1y7hM7mtlSzY9ZQ0P7dU7pDPhh7W3e2rRDIyBX9yCYi5ScUYeEUuVlK7gIaqBnAWjWpPdV7LSfd+hBlCEOEYtD2Ta1J1xASonXeFoaYFnGF18azrRIiDoPkNK2sQosCNnkVJHS8Wx/yCV2k/8LnjCWD1wCVq/pA3G18HRiYUgZOb6z9y2xhaRcwcvAOfxDp01x/Mmhw+SDF7hlqNyTkSzikiYEedk=
  file: 
  - _build/CollectiveDecentralizedJudgements.pdf
  skip_cleanup: false
  on:
    tags: true
